#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 표준출력(현재 쉘을 실행한 콘솔이나 터미널)을 변수에 저장 
COMMIT_MESSAGE_FILE_PATH=$1

# TODO merge 할 때도 생성되니까 그 부분 삭제할 수 있도록

# grep으로 현재 브랜치 긁어오고 sed로 자름
TYPE=$(git branch | grep '*' | sed 's/* //' | sed 's/\([^/]*\).*/\1/')
# ISSUENUMBER=$(git branch | grep '\*' | sed 's/* //' | sed 's/^.*\///' | sed 's/^\([^-]*-[^-]*\).*/\1/')
ISSUENUMBER=$(git branch | grep '*' | sed 's/* //' | sed 's/^.*\///')
echo "$TYPE(#$ISSUENUMBER): $(cat "$COMMIT_MESSAGE_FILE_PATH")" > "$COMMIT_MESSAGE_FILE_PATH"
echo "$(cat .gitmessage.txt)" >> "$COMMIT_MESSAGE_FILE_PATH"