name: Release

# main으로 가는 PR이 closed될 때 실행
on:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  Release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.9

        # release/1.0.0 식인 브랜치이름에서 숫자만 떼서 릴리즈 번호로 사용
      - name: 버전 정보 추출(from Branch Name)
        run: echo "TAG=$(echo '${{ steps.branch-name.outputs.current_branch }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_ENV

      - name: echo current branch name
        run: echo "current branch name - ${{ env.TAG }}"

      - name: Release & Tag 생성
        if: github.event.pull_request.merged == true  # PR인 경우에만
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}